#WS CONFIGURATION
host: http://localhost
port: 8182
ws_path: ws   
ws_timeup: 60
#DP2 launch config 

exec_line_nix: ../Main/dp2ws_local.sh  
exec_line_win: ..\Main\dp2ws_local.bat  
local: false
authenticate: true
# ROBOT CONF
client_key: clientkey
client_secret: supersecret
#connection settings
timeout_seconds: 100
