#WS CONFIGURATION
host: ${pipeline.ws.host}
port: ${pipeline.ws.port}
ws_path: ${pipeline.ws.path}
ws_timeup: ${pipeline.ws.timeout}
#DP2 launch config 
exec_line_nix: ${pipeline.ws.cmd.unix}
exec_line_win: ${pipeline.ws.cmd.win}  
local: ${pipeline.ws.local}
authenticate: ${pipeline.ws.authenticate}
# ROBOT CONF
client_key: ${pipeline.ws.clientkey}
client_secret: ${pipeline.ws.clientsecret}
#connection settings
timeout_seconds: ${pipeline.cli.timeout}
#debug
debug: ${pipeline.cli.debug}
